In [1]:
import os
import numpy as np
import pandas as pd
import pickle
import heapq
from HMM import *

def save_pickle(obj, name):
    with open("obj/" + name + ".pkl", "wb") as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_pickle(name):
    with open("obj/" + name + ".pkl", "rb") as f:
        return pickle.load(f)

Obtained list of possible tags from the trng set - 21 tags
Obtained list of vocab from the trng set - 18212 words
               B-NP      I-NP      B-VP    B-ADVP    B-ADJP    I-ADJP  \
##START##  0.648049  0.000000  0.018661  0.054287  0.003262  0.000000   
B-NP       0.028898  0.684706  0.130303  0.009809  0.003213  0.000000   
I-NP       0.047645  0.406679  0.134912  0.015332  0.004103  0.000000   
B-VP       0.345217  0.000000  0.007229  0.031214  0.039209  0.000000   
B-ADVP     0.210379  0.000000  0.215989  0.016269  0.016550  0.000000   
B-ADJP     0.051970  0.000000  0.110794  0.015991  0.001142  0.279840   
I-ADJP     0.088850  0.000000  0.069686  0.013937  0.012195  0.146341   
B-PP       0.928047  0.000000  0.026595  0.003318  0.002611  0.000000   
O          0.347185  0.000000  0.115030  0.029197  0.008755  0.000000   
B-SBAR     0.872565  0.000000  0.038441  0.008952  0.003160  0.000000   
I-VP       0.355350  0.000000  0.008269  0.037602  0.029038  0.000000   
I-ADVP    

## Part 2
This part deals with the estimation of the emission parameters using MLE. Refer to HMM.py for all the functions being referenced.

<img src="screenshots/p2_1.png">

```calc_emission_pairwise(df, word, tag)```

<img src="screenshots/p2_2.png">

```calc_emission_UNK_pairwise(df, word, tag, k=0.5)```

<img src="screenshots/p2_3.png">
Functions referenced can be found in HMM.py. Run the following script:

In [ ]:
datasets = ["CN", "EN", "SG"]

In [ ]:
dataset = "CN"
traindf = read_train_data(dataset)
possible_tags = get_tags(traindf)
vocab = get_vocab(traindf)
vocab.append("#UNK#")
# print(possible_tags)
# print(vocab)

emission_parameters = calc_all_emission_paras(dataset, traindf, possible_tags, vocab)
predict_dict = get_predictions_dict(possible_tags, vocab, emission_parameters)

dev_in = read_input_data(dataset, vocab)

dev_in["tag"] = dev_in["unseen"].map(predict_dict)
dev_in["tag"] = dev_in["tag"].fillna("")
preddf = dev_in.drop(["unseen"], axis=1)

preddf.to_csv(dataset + "/dev.p2.out", header=None, index=None, sep=" ", mode="w")
print(f'Write output for {dataset} done at "{dataset}/dev.p2.out"')

# save_pickle(emission_parameters, dataset + "_emission_paras")
# save_pickle(predict_dict, dataset + "_pred_dict")

In [ ]:
dataset = "EN"
traindf = read_train_data(dataset)
possible_tags = get_tags(traindf)
vocab = get_vocab(traindf)
vocab.append("#UNK#")
# print(possible_tags)
# print(vocab)

emission_parameters = calc_all_emission_paras(dataset, traindf, possible_tags, vocab)
predict_dict = get_predictions_dict(possible_tags, vocab, emission_parameters)

dev_in = read_input_data(dataset, vocab)

dev_in["tag"] = dev_in["unseen"].map(predict_dict)
dev_in["tag"] = dev_in["tag"].fillna("")
preddf = dev_in.drop(["unseen"], axis=1)

preddf.to_csv(dataset + "/dev.p2.out", header=None, index=None, sep=" ", mode="w")
print(f'Write output for {dataset} done at "{dataset}/dev.p2.out"')


# save_pickle(emission_parameters, dataset + "_emission_paras")
# save_pickle(predict_dict, dataset + "_pred_dict")

In [ ]:
dataset = "SG"
traindf = read_train_data(dataset)
possible_tags = get_tags(traindf)
vocab = get_vocab(traindf)
vocab.append("#UNK#")
# print(possible_tags)
# print(vocab)

emission_parameters = calc_all_emission_paras(dataset, traindf, possible_tags, vocab)
predict_dict = get_predictions_dict(possible_tags, vocab, emission_parameters)

dev_in = read_input_data(dataset, vocab)

dev_in["tag"] = dev_in["unseen"].map(predict_dict)
dev_in["tag"] = dev_in["tag"].fillna("")
preddf = dev_in.drop(["unseen"], axis=1)

preddf.to_csv(dataset + "/dev.p2.out", header=None, index=None, sep=" ", mode="w")
print(f'Write output for {dataset} done at "{dataset}/dev.p2.out"')

# save_pickle(emission_parameters, dataset + "_emission_paras")
# save_pickle(predict_dict, dataset + "_pred_dict")

In [ ]:
print('CN')
!python3 EvalScript/evalResult.py CN/dev.out CN/dev.p2.out

print('EN')
!python3 EvalScript/evalResult.py EN/dev.out EN/dev.p2.out

print('SG')
!python3 EvalScript/evalResult.py SG/dev.out SG/dev.p2.out

## Part 3
This part deals with the estimation of the transmission parameters using MLE. Refer to HMM.py for all the functions being referenced.

### Estimate transition parameters

<img src="screenshots/p3_1.png">

In [13]:
datasets = ["CN", "EN", "SG"]

In [14]:
# datasets = ["EN"]
for dataset in datasets:
    print(f'-----Estimating transmission parameters for {dataset}-----')
    traindf = read_train_data(dataset)
    possible_tags = get_tags(traindf)
    vocab = get_vocab(traindf)

    full_tags_list = read_train_file(dataset) # get full list of tags

    trans_para = transition_para(full_tags_list, possible_tags)
    trans_arr = trans_para.to_numpy()
    pi0 = trans_arr[0]
    a = np.delete(trans_arr, 0, 0)
    a = np.delete(a,len(a[0])-1,1)
    print(f'Completed for {dataset}')

    save_pickle(trans_para, dataset+'_transmissionparas')
    save_pickle(a, dataset+'_a')
    save_pickle(pi0, dataset+'_pi0')

-----Estimating transmission parameters for CN-----
Obtained list of possible tags from the trng set - 7 tags
Obtained list of vocab from the trng set - 16935 words
Completed for CN
-----Estimating transmission parameters for EN-----
Obtained list of possible tags from the trng set - 21 tags
Obtained list of vocab from the trng set - 18212 words
Completed for EN
-----Estimating transmission parameters for SG-----
Obtained list of possible tags from the trng set - 7 tags
Obtained list of vocab from the trng set - 42809 words
Completed for SG


## Part 3

### Viterbi algorithm
<img src="screenshots/p3_2.png">

### load parameters

In [2]:
dataset = 'EN'

traindf = read_train_data(dataset)
possible_tags = get_tags(traindf)
vocab = get_vocab(traindf)
vocab.append('#UNK#')

datalist = read_train_file(dataset)

obs_map = {k: v for v, k in enumerate(vocab)}
state_map = {k: v for v, k in enumerate(possible_tags)}

pi = load_pickle(dataset+'_pi0')

a = load_pickle(dataset+'_a')
b = load_pickle(dataset+'_emissionparas')

obs = list(range(len(vocab)))

Obtained list of possible tags from the trng set - 21 tags
Obtained list of vocab from the trng set - 18212 words


In [3]:
#print(obs_map)
print(state_map)
#print(pi)
#print(a)
#print(b)
#print(obs)

{'B-NP': 0, 'I-NP': 1, 'B-VP': 2, 'B-ADVP': 3, 'B-ADJP': 4, 'I-ADJP': 5, 'B-PP': 6, 'O': 7, 'B-SBAR': 8, 'I-VP': 9, 'I-ADVP': 10, 'B-PRT': 11, 'I-PP': 12, 'B-CONJP': 13, 'I-CONJP': 14, 'B-INTJ': 15, 'I-INTJ': 16, 'I-SBAR': 17, 'B-UCP': 18, 'I-UCP': 19, 'B-LST': 20}


## Part 4
We need to use the estimated transition and emission parameters to implement an algorithm to find the 3rd best output sequences.

This problem to find k-best sequences is conventionally known as List Viterbi Decoding.

Refer to HMM.py for the implementation - `kViterbiParallel`

In the implementation,
- `Heapq` is used as p,riority queue. Every pop gives the smallest heap element for heap sort.
- `Rank` is keep track of consistent optimal transitions as the most k optimal path will not deviate much

We will be using the parallel LVA (List Viterbi Algorithm). The process is divided into 4 steps.

**1.Initialisation**

$\begin{array}{l}\phi_{t}(i, k)=c_{1}(1, i) \\ \xi_{t}(i, k)=1, \quad 1 \leq i \leq N, \quad 1 \leq k \leq L\end{array}$


**2. Recursion and Termination $(1<t \leq M)$**

$\phi_{t}(i, k)=\min _{1 \leq j \leq N \atop 1 \leq l \leq L}\left[\phi_{t-1}(j, l)+c_{t}(j, i)\right], \quad 1 \leq i \leq N$

where $min^{k}$ denotes the $k^{th}$ smallest value

$\left(j^{*}, l^{*}\right)=\underset{1 \leq j \leq N}{\arg \min }^{(k)}\left[\phi_{t-1}(j, l)+c_{t}(j, i)\right], 1 \leq i \leq N$

Here $j^{*}$ is the predecessor state for the $k^{th}$ best path into state $i$ and $l^{*}$ is the corresponding ranking

$\\ \begin{array}{l}\xi_{t}(i, k)=j^{*} \\ \gamma_{t}(i, k)=l^{*}\end{array}$


**3. Path Backtracking**

The $k^{th}$ best sequence is

$\left(1, j_{1}, j_{2}, \ldots, j_{M-1}, 1\right)$

where

$\begin{array}{l}j_{t}=\xi_{t+1}\left(j_{t+1}, l_{t+1}\right) \\ l_{t}=r_{t+1}\left(j_{t+1}, l_{t+1}\right) \\ j_{M-1}=\xi_{M}(1, k)\end{array}$

and

$l_{M-1}=r_{M}(1, k)$

In [4]:
### Part 4 Testing ###
number_to_tag_dict = {y:x for x,y in state_map.items()}
number_to_word_dict = {y:x for x,y in obs_map.items()}

test_coll = ['I','love','you']
obs = list(map(lambda x: obs_map.get(x), test_coll))
print(obs)

[185, 1110, 246]


In [5]:
path, delta, phi, max_prob = viterbi2(pi, a, b, obs)
print(path)
tag_path = list(map(lambda x: number_to_tag_dict.get(x), path))
print(tag_path)

[0 1 0]
['B-NP', 'I-NP', 'B-NP']


In [6]:
obs2 = list(range(0,11))
print(obs2)
test_coll_2 = list(map(lambda x: number_to_word_dict.get(x), obs2))
print(test_coll_2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
['Municipal', 'bonds', 'are', 'generally', 'a', 'bit', 'safer', 'than', 'corporate', 'in', 'recession']


In [7]:
path, delta, phi, max_prob = kViterbiParallel(pi, a, b, obs2, 3)
print(path)
tag_path = list(map(lambda x: number_to_tag_dict.get(x), path[2]))
print(tag_path)

[[0 1 2 3 4 5 5 6 0 6 0]
 [0 1 2 9 4 5 5 6 0 6 0]
 [0 1 2 3 4 5 5 8 0 6 0]]
['B-NP', 'I-NP', 'B-VP', 'B-ADVP', 'B-ADJP', 'I-ADJP', 'I-ADJP', 'B-SBAR', 'B-NP', 'B-PP', 'B-NP']
